config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

    resources :accounts, :appointments, :services

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password

  has_many :appointments
  has_many :services, through: :appointments
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :account
  belongs_to :service

  validates :date, presence: true
  validates :hour, presence: true
end

app/models/service.rb
require "money_attributes"
class Service < ActiveRecord::Base
  include MoneyAttributes
  money_attributes :price

  has_many :appointments
  has_many :accounts, through: :appointments
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:notice] = "Account successfully created."
      redirect_to @account
    else
      flash[:alert] = "Failed to create account. Please try again."
      render :new
    end
  end

private

  def account_params
    params.require(:account).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = Appointment.all
    date_from_ajax = params[:matched_date]
    reduce = Appointment.where(:date => date_from_ajax)
    @new_dates = reduce.collect {|x| x.hour.gsub(/\D/, '').rjust(4, "0")}
    render json: @new_dates
  end

  def new
    @appointment = Appointment.new
    @service_names = Service.all.each_with_index.map { |service, i| [service.name, i] }
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    puts "PARAMS HERE\n\n\n\n\n"
    p appointment_params
    @appointment = Appointment.create(appointment_params)
    if @appointment.save
      redirect_to new_appointment_path
    else
      err = ''
      @appointment.errors.full_messages.each do |m|
        err << m
      end

      redirect_to new_appointment_path, :flash => { :alert => "#{err}, please try again" }
    end
  end

private

  def appointment_params
    params.require(:appointment).permit!
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/index.html.erb
Hello World!

<% @accounts.each_with_index do |a, i| %>
  <p>
    Member ID: <%= i %>
    <%= a.fname %> <%= a.lname %>
  </p>
<% end %>

<h3><%= link_to('Create Account', new_account_path) %></h3>
<h3><%= link_to('Create Appointment', new_appointment_path) %></h3>

app/views/accounts/new.html.erb
<div class="center-block col-lg-6">
  <h3>Create New Account</h3>

  <% if flash[:alert] %>
  <h2 class="notice"><%= flash[:alert] %></h2>
  <% end %>

  <% if @account.errors.any? %>
    <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
    <%= simple_form_for @account, html: { class: 'form-horizontal', id: 'create-account-form' } do |f| %>
      <%= f.input :fname, label: 'First Name' %>
      <%= f.input :lname, label: 'Last Name' %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :birthdate, label: 'Birth Day' %>
      <%= f.input :phone %>
      <%= f.input :address %>
      <%= f.input :memo %>
      <%= f.submit %>
    <% end %><br>

  <%= link_to('Home', root_path) %>
</div>

app/views/accounts/show.html.erb
Account show page
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h1><%= "#{@account.fname.capitalize} #{@account.lname.capitalize}" %></h1>

<p>Birthday: <%= @account.birthdate %></p>
<p>Phone: <%= @account.phone %></p>
<p>Memo: <%= @account.memo %></p>

app/views/appointments/_hour_picker.html.erb
<div class="col-sm-3 center-block" id="hour_picker">
      <table class="table table-striped table-hover" border="1">
        <tr>
          <th class="selected_date"></th>
        </tr>
        <tr class="cal_table2">
          <td class="0700">7:00 am</td>
        </tr>
        <tr class="cal_table2">
          <td class="0800">8:00 am</td>
        </tr>
        <tr class="cal_table2">
          <td class="0900">9:00 am</td>
        </tr>
        <tr class="cal_table2">
          <td class="1000">10:00 am</td>
        </tr>
        <tr class="cal_table2">
          <td class="1100">11:00 am</td>
        </tr>
        <tr class="cal_table2">
          <td class="1200">12:00 pm</td>
        </tr>
        <tr class="cal_table2">
          <td class="0100">1:00 pm</td>
        </tr>
        <tr class="cal_table2">
          <td class="0200">2:00 pm</td>
        </tr>
        <tr class="cal_table2">
          <td class="0300">3:00 pm</td>
        </tr>
        <tr class="cal_table2">
          <td class="0400">4:00 pm</td>
        </tr>
        <tr class="cal_table2">
          <td class="0500">5:00 pm</td>
        </tr>
        <tr class="cal_table2">
          <td class="0600">6:00 pm</td>
        </tr>

        <tr class="cal_table3">
          <td class="cal_previous"><form method="link" action="/appointments/new"><button class="btn btn-success">Reset</button></form></td>
        </tr>
      </table>
    </div>

app/views/appointments/new.html.erb
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
</head>

<div class="center-block col-lg-4">
  <h3>Create New Appointment</h3>

  <% if flash[:alert] %>
  <h2 class="notice"><%= flash[:alert] %></h2>
  <% end %>

  <% if @appointment.errors.any? %>
    <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= simple_form_for(@appointment, html: { class: 'form-horizontal', id:'appointment-form' }) do |f| %>

    <%= f.input :service_id do %>
      <%= f.select :service_id, options_for_select(@service_names) %>
    <% end %>

    <%= f.input :date, placeholder: "#{Date.today}", input_html: { id: 'datepicker' } %>

    <%= f.input :hour, placeholder: '12:00 pm' %>

    <%= f.submit "Create Appointment", :id => 'submit_form', :style => "display: none;" %>
  <% end %>

  <%= render "hour_picker" %>

  <%= link_to('Home', root_path) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Zen Spa</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag :modernizr %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Zen Spa</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-default">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
      <%= yield %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/services/index.html.erb
Hello World!

<% @services.each_with_index do |a, i| %>
  <p>
    Member ID: <%= i %>
    <%= a.name %> <%= a.price_money %>
  </p>
<% end %>

<h3><%= link_to('Create Account', new_account_path) %></h3>
<h3><%= link_to('Create Appointment', new_appointment_path) %></h3>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>Zen Spa</title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    </head>
    <body class="loading">

        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
      <main>
        <section id="slide-1" class="homeSlide">
            <div class="bcg" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -100px;" data-anchor-target="#slide-1">
              <div class="hsContainer">
              <div class="hsContent" data-center="opacity: 1" data-106-top="opacity: 0" data-anchor-target="#slide-1 h2">
                <h1>Manicure</h1>
                <h2>You’ve never looked so polished!</h2>
                <p>This classic manicure includes nail shaping, cuticle care and a moisturizing massage.</p>
              </div>
              </div>
            </div>
        </section>

        <section id="slide-2">
          <div class="bcg" data-0="background-color:rgb(83,0,59);" data-top="background-color:(0,0,0);"  data-anchor-target="#slide-2">
            <div class="hsContainer">
              <div class="hsContent">
                <h2 data-center="opacity: 1" data--200-bottom="opacity: 0" data-206-top="opacity: 1" data-106-top="opacity: 0" data-anchor-target="#slide-2 h2">Explore</h2>
                <p data-center="opacity: 1" data--200-bottom="opacity: 0" data-206-top="opacity: 1" data-106-top="opacity: 0" data-anchor-target="#slide-2 h2">Continue scrolling to discover more ways to spoil yourself.</p>
              </div>
              </div>
          </div>
        </section>

        <section id="slide-3" class="homeSlide">
          <div class="bcg" data-center="background-position: 0px 50%;" data-bottom-top="background-position: 0px 40%;" data-top-bottom="background-position: -40px 50%;" data-anchor-target="#slide-3">
              <div class="hsContainer">
                <div class="hsContent">
                  <div class="plaxEl" data-106-top="opacity: 0" data--30p-top="opacity: 1;" data--60p-top="opacity: 0;" data-bottom="opacity: 1; position: fixed; top: 206px; width: 100%; left: 0;"  data-anchor-target="#slide-3">
                    <h2>Feeling velvety soft</h2>
                    <p>Enjoy one of our luxury body treatments for skin that radiates with health and is soft to the touch. Carefully balanced to both deeply cleanse and replenish, our body treatments lift the veil of dullness and dryness to restore hydrated silkiness to skin.</p>
                  </div>
                </div>
              </div>

            </div>
        </section>

        <section id="slide-4" class="homeSlide homeSlideTall">
          <div class="bcg" data-center="background-position: 50% 0px;" data-bottom-top="background-position: 50% 100px;" data-top-bottom="background-position: 50% -100px;" data-anchor-target="#slide-4">
            <div class="curtainContainer">

              <div class="curtain" data-bottom-top="opacity: 0" data-106-top="height: 1%; opacity: 0; top: -10%;" data-center="height: 100%; opacity: 0.5; top: 0%;" data-anchor-target="#slide-4"></div>
              <div class="copy" data-bottom-top="opacity: 0" data--100-bottom="opacity: 0" data--280-bottom="opacity: 1;" data-280-top="opacity: 1;" data-106-top="opacity: 0;" data-anchor-target="#slide-4 .copy">
                <h2>Palette Of Therapies</h2>
                <p>Revitalize your skin, relax your mind and discover a dramatic improvement in your appearance with our medically advanced spa facial therapies.</p>
              </div>

            </div>
          </div>
        </section>

        <section id="slide-5" class="homeSlide homeSlideTall2">
          <div class="bcg">
            &nbsp;
          </div>
          <div class="bcg bcg2" data-bottom-top="opacity: 0;" data--33p-top="opacity: 0;" data--66p-top="opacity: 1;" data-anchor-target="#slide-5">
            <div class="hsContainer">
              <div class="hsContent" data-bottom-top="opacity: 0;" data-center="opacity: 1" data-anchor-target="#slide-5">
                <h2>Wrap it up!</h2>
                <p>All of our scrubs and wraps are made with natural ingredients and are identically priced.</p>
              </div>
            </div>
          </div>
          <div class="bcg bcg3" data-300-bottom="opacity: 0;" data-100-bottom="opacity: 1;" data-anchor-target="#slide-5">
            <div class="hsContainer">
              <div class="hsContent" data-100-bottom="opacity: 0;" data-bottom="opacity: 1;" data-anchor-target="#slide-5">
                <h2>Ready?</h2>
                <p>Click <a href="/appointments/new" target="_blank">here</a> to start your rejuvenating spa journey today.</p>
              </div>
            </div>
          </div>
        </section>
    </main>
  </body>
</html>